# Generated by Django 5.1.5 on 2025-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_support_percentage_donation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='support_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='support_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
