# Generated by Django 5.1.5 on 2025-01-29 20:13

import django.db.models.deletion
import phonenumber_field.modelfields
import publications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('medicine', 'Медицина'), ('emergency', 'Неотложная помощь'), ('charity', 'Благотворительность'), ('education', 'Образование'), ('animals', 'Животные'), ('ecology', 'Экология'), ('sports', 'Спорт'), ('general', 'Общий сбор средств')], max_length=50)),
                ('description', models.TextField(max_length=3000)),
                ('bank_details', models.TextField(max_length=1000, validators=[publications.models.validate_bank_details])),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма, которую необходимо собрать.', max_digits=10)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publications/images/', validators=[publications.models.validate_file_size, publications.models.validate_image_format])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='publications/videos/', validators=[publications.models.validate_file_size, publications.models.validate_video_format])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications.publication')),
            ],
        ),
    ]
