# Generated by Django 5.1.5 on 2025-02-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_donation_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_phone',
        ),
    ]
