# Generated by Django 5.1.5 on 2025-02-05 12:10

import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_donation_donor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bank_details',
            field=models.CharField(max_length=30, validators=[publications.models.validate_bank_details]),
        ),
    ]
