# Generated by Django 5.1.5 on 2025-03-13 15:36

import django.db.models.deletion
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', 'Удостоверение личности'), ('income', 'Справка о доходах'), ('supporting', 'Подтверждающие документы')], max_length=20)),
                ('file', models.FileField(upload_to=publications.models.publication_document_path, validators=[publications.models.validate_document_format, publications.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='publications.publication')),
            ],
        ),
    ]
