# Generated by Django 5.1.5 on 2025-03-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_donation_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
