# Generated by Django 5.1.5 on 2025-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationdocument',
            name='verification_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationdocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Ожидание проверки'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='publicationdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
