# Generated by Django 5.1.5 on 2025-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publicationdocument_verification_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationdocument',
            name='text_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
