# Generated by Django 5.1.5 on 2025-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_publicationdocument_text_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationdocument',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
