# Generated by Django 5.1.5 on 2025-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_publicationdocument_extracted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='duration_days',
            field=models.IntegerField(choices=[(7, '7 дней'), (14, '2 недели'), (30, '1 месяц')], default=30),
        ),
        migrations.AddField(
            model_name='publication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('successful', 'Успешно завершена'), ('expired', 'Истёк срок')], default='active', max_length=20),
        ),
    ]
