# Generated by Django 5.1.5 on 2025-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_publication_duration_days_publication_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', help_text='Статус проверки всех загруженных документов', max_length=20),
        ),
    ]
