# Generated by Django 5.1.5 on 2025-04-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_publication_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('successful', 'Успешно завершена'), ('pending', 'Ожидает проверки'), ('expired', 'Истёк срок')], default='active', max_length=20),
        ),
    ]
